server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  application:
    name: fbgb-springboot
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB